ERROR - 2022-10-17 01:20:48 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'logistikptajs' in C:\Users\Lisa\Desktop\silogajs\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\Users\Lisa\Desktop\silogajs\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'logistikptajs', 3306, '', 0)
#1 C:\Users\Lisa\Desktop\silogajs\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Lisa\Desktop\silogajs\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Lisa\Desktop\silogajs\app\Models\M_Auth.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\Users\Lisa\Desktop\silogajs\app\Controllers\C_Auth.php(25): App\Models\M_Auth->query_validasi_id_user('ADM001')
#5 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(904): App\Controllers\C_Auth->proses_login()
#6 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_Auth))
#7 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\Lisa\Desktop\silogajs\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\Users\Lisa\Desktop\silogajs\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Lisa\\D...')
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'logistikptajs' in C:\Users\Lisa\Desktop\silogajs\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\Users\Lisa\Desktop\silogajs\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Lisa\Desktop\silogajs\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Lisa\Desktop\silogajs\app\Models\M_Auth.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\Users\Lisa\Desktop\silogajs\app\Controllers\C_Auth.php(25): App\Models\M_Auth->query_validasi_id_user('ADM001')
#4 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(904): App\Controllers\C_Auth->proses_login()
#5 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_Auth))
#6 C:\Users\Lisa\Desktop\silogajs\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\Lisa\Desktop\silogajs\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\Users\Lisa\Desktop\silogajs\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Lisa\\D...')
#9 {main}
CRITICAL - 2022-10-17 01:20:49 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'logistikptajs'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\M_Auth.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM user WHERE id_user=\'ADM001\' LIMIT 1')
 3 APPPATH\Controllers\C_Auth.php(25): App\Models\M_Auth->query_validasi_id_user('ADM001')
 4 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\C_Auth->proses_login()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_Auth))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
